[programs.localnet]
drip = { address="dripTrkvSyQKvkyWg7oi4jmeEGMA5scSYowHArJ9Vwk", idl="./target/idl/drip.json" }

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# Load other programs into anchor
[[test.genesis]]
address = "SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8"
program = "./deps/spl_token_swap/spl_token_swap.so"
