[programs.localnet]
drip = { address="dripTrkvSyQKvkyWg7oi4jmeEGMA5scSYowHArJ9Vwk", idl="./target/idl/drip.json" }

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
# TODO(Mocha): Remove below and uncomment the other line
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --parallel tests/integration-tests/dripOrcaWhirlpool.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --parallel tests/integration-tests/*.ts"

# Load other programs into anchor
[[test.genesis]]
address = "SwaPpA9LAaLfeLi3a68M4DjnLqgtticKg6CnyNwgAC8"
program = "./deps/spl_token_swap/spl_token_swap.so"

[[test.genesis]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
program = "./deps/orca_whirlpool/whirlpool.so"
