[programs.localnet]
drip = { address="dripTrkvSyQKvkyWg7oi4jmeEGMA5scSYowHArJ9Vwk", idl="./target/idl/drip.json" }
whirlpool = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc" 

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 --parallel"

# Load other programs into anchor
[[test.genesis]]
address = "SwapsVeCiPHMUAtzQWZw7RjsKjgCjhwU55QGu4U1Szw"
program = "./deps/spl_token_swap/spl_token_swap.so"

[[test.genesis]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
program = "./deps/orca_whirlpool/whirlpool.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/mpl_token_metadata/mpl_token_metadata.so"
