[package]
name = "drip"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "drip"
doctest = false

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.24.2"
anchor-spl = "0.24.2"
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
spl-token-swap = { version = "2.0.0", features = ["no-entrypoint", "production"] }
whirlpool = { git = "https://github.com/orca-so/whirlpools.git", features = ["cpi"] }

[dev-dependencies]
test-case = "2.0.0"
