#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Checking rust formatting... Run 'cargo fmt' if this check fails"
cargo fmt -- --check

echo "Checking typescript formatting... Run 'yarn run prettier --w ./' if this check fails"
yarn run prettier --c ./

echo "Running cargo tests"
cargo test

echo "Running anchor tests"
anchor test | tee .anchor/test.logs
! cat .anchor/test.logs | grep failing
