#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Checking rust formatting... Run 'cargo fmt' if this check fails"
cargo fmt -- --check

echo "Checking typescript formatting... Run 'prettier --w ./' if this check fails"
yarn run prettier --c ./

echo "Running cargo tests"
cargo test

echo "Running anchor tests"
! anchor test | tee /dev/stdout | grep failing > /dev/null
