name: CI
env:
  cli-id: anchor-v0.24.2.dev-7b86aed-solana-1.10.5
  SWAP_PROGRAM_OWNER_FEE_ADDRESS: HfoTxFR1Tm6kGmWgYWD6J7YHVy1UwqSULUGVLXkJqaKN
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - name: ⚡️ Cache
        id: cache-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            /opt/hostedtoolcache/node
            target
            node_modules

      - name: Setup Rust
        id: install-rust-toolchain
        if: steps.cache-deps.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.32.0

      - name: Install OS Deps
        id: install-os-deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev

      - name: Install Solana Tools
        id: install-solana-tools
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.10.5/install)"

      - name: Add Solana Tools to Path
        run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - name: Install Node Deps
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          npm install -g @project-serum/anchor-cli@0.24.2
          npm install -g typescript
          npm install -g yarn
          npm install -g ts-mocha
          npm install -g @project-serum/anchor
          yarn

      - run: npm list -g

      - name: Build Programs
        run: anchor build

  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚡️ Cache
        id: cache-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            /opt/hostedtoolcache/node
            target
            node_modules

      - run: cargo fmt -- --check
      - run: yarn run prettier --c ./

  test-unit:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚡️ Cache
        id: cache-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            /opt/hostedtoolcache/node
            target
            node_modules

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - run: cargo test

  test-integration-batch-1:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚡️ Cache
        id: cache-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            /opt/hostedtoolcache/node
            target
            node_modules

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
      - name: Create Test Wallet
        run: solana-keygen new --no-bip39-passphrase
      - run: anchor test tests/integration-tests/batch1/*.ts

  test-integration-batch-2:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚡️ Cache
        id: cache-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            /opt/hostedtoolcache/node
            target
            node_modules

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
      - name: Create Test Wallet
        run: solana-keygen new --no-bip39-passphrase
      - run: anchor test tests/integration-tests/batch2/*.ts

  test-integration-batch-3:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚡️ Cache
        id: cache-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            /opt/hostedtoolcache/node
            target
            node_modules

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
      - name: Create Test Wallet
        run: solana-keygen new --no-bip39-passphrase
      - run: anchor test tests/integration-tests/batch3/*.ts

  test-integration-batch-4:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚡️ Cache
        id: cache-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            /opt/hostedtoolcache/node
            target
            node_modules

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV
      - name: Create Test Wallet
        run: solana-keygen new --no-bip39-passphrase
      - run: anchor test tests/integration-tests/batch4/*.ts
  
  audit:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check-out the repository
        uses: actions/checkout@v2

      - name: ⚡️ Cache
        id: cache-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            /opt/hostedtoolcache/node
            target
            node_modules

      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - name: Soteria Audit
        continue-on-error: false          
        uses: silas-x/soteria-action@main
        with:                             
          solana-version: "1.10.5"        
          run-mode: "-analyzeAll"         
          cargo-com: "."                  
          program-path: "programs/drip" 