const MS_IN_A_SECOND = 1000;
const SECONDS_IN_A_MINUTE = 60;
const MINUTES_IN_AN_HOUR = 60;
const HOURS_IN_A_DAY = 24;
const DAYS_IN_A_WEEK = 7;
const DAYS_IN_A_MONTH = 30;

const MS_IN_A_DAY = MS_IN_A_SECOND * SECONDS_IN_A_MINUTE * MINUTES_IN_AN_HOUR * HOURS_IN_A_DAY;
const MS_IN_A_WEEK = MS_IN_A_DAY * DAYS_IN_A_WEEK;
const MS_IN_A_MONTH = MS_IN_A_DAY * DAYS_IN_A_MONTH;

export enum Granularity {
  DAILY = MS_IN_A_DAY,
  WEEKLY = MS_IN_A_WEEK,
  MONTHLY = MS_IN_A_MONTH,
}