const SECONDS_IN_A_MINUTE = 60;
const MINUTES_IN_AN_HOUR = 60;
const HOURS_IN_A_DAY = 24;
const DAYS_IN_A_YEAR = 365.25;
const SECONDS_IN_A_YEAR =
  DAYS_IN_A_YEAR * HOURS_IN_A_DAY * MINUTES_IN_AN_HOUR * SECONDS_IN_A_MINUTE;
const WEEKS_IN_A_YEAR = 52;
const MONTHS_IN_A_YEAR = 12;

const SECONDS_IN_A_DAY =
  SECONDS_IN_A_MINUTE * MINUTES_IN_AN_HOUR * HOURS_IN_A_DAY;
const SECONDS_IN_A_WEEK = SECONDS_IN_A_YEAR / WEEKS_IN_A_YEAR;
const SECONDS_IN_A_MONTH = SECONDS_IN_A_YEAR / MONTHS_IN_A_YEAR;

export enum Granularity {
  DAILY = SECONDS_IN_A_DAY,
  WEEKLY = SECONDS_IN_A_WEEK,
  MONTHLY = SECONDS_IN_A_MONTH,
}
